// import "./class/day18125";
// import "./class/day18127";
// import "babel-polyfill";
// import "./class/string-expansion";
// import "./class/NumberExpansion";
// import "./class/array";
// import "./class/fns";
// import "./class/objects";
// import "./class/symbols";
// import "./class/set-map";
// import "./class/map-set-array";
// import "./class/proxys";
// import "./class/classObject";
// import './class/promises';
// import "./class/Iterator";
import './class/genertaors';